name: PR Preview Cleanup

on:
  pull_request:
    types: [closed]

env:
  AWS_REGION: us-east-1

jobs:
  teardown-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - run: yarn install --frozen-lockfile
      - name: Destroy preview stacks
        run: |
          cd packages/infra
          npx cdk destroy \
            scrappr-ui-pr-${{ github.event.pull_request.number }} \
            scrappr-api-pr-${{ github.event.pull_request.number }} \
            scrappr-storage-pr-${{ github.event.pull_request.number }} \
            --force -c env=pr-${{ github.event.pull_request.number }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          VITE_USER_POOL_ID: ${{ secrets.VITE_USER_POOL_ID }}
          VITE_USER_POOL_CLIENT_ID: ${{ secrets.VITE_USER_POOL_CLIENT_ID }}
